### PR TITLE
RPI eth0/wlan0 as boardid from serial number

### PR DESCRIPTION
**Pull request by dognotdog**
This implements #19 for both wlan0 and eth0 on Raspberry Pis up to the RPI4.

### CODE REVIEW

**Comment by fhunleth** [comment]
This looks pretty good on a quick skim. Thanks! 

I'll try it out soon and hopefully get it merged and released in not too long.

**Comment by fhunleth** [comment]
It looks like the Raspberry Pi Foundation has a 3rd OUI: `E4:5F:01`. See https://udger.com/resources/mac-address-vendor-detail?name=raspberry_pi_foundation. 

I wish there were a way of figuring out which one they used without deferring to the user to specify RPI or RPI4. I'm sure it's simple and just a matter of finding the "secret" like the 0x555555 thing. I'll give it a few more searches. If nothing turns up, I'll go with what you posted since it's way better than nothing and will work for Nerves.

**Comment by dognotdog** [comment]
Maybe it can eventually be split into more arguments, the `oui` plus a `magic` number, where, they accept either hex or descriptive string, like `$ boardid -b rpi -o rpi4 -m wlan0` or `$ boardid -b rpi -o E4:5F:01 -m 55:55:55`, but that seems like it would require deeper structural changes?

Though if the board type would be autodetected, or the MAC OUI could be grabbed from somewhere in the system, that'd reduce the UI complexity.

Personally, I would not worry too much about that until an actual board comes out that has that 3rd RPI OUI, even if it might mean some extra cruft to deal with API compatibility.

**Comment by fhunleth** [comment]
I'd prefer less arguments to minimize confusion. Could you do some research for how the RPi Foundation chooses which OUI to use? Perhaps it's a simple check like serial numbers < x use the original OUI and everything else uses the new one?

**Comment by dognotdog** [comment]
Doesn't seem like that happens with any regularity, they just did the new OUI for the rpi4, but MAC addresses aren't guaranteed to be collision free.

Seems like the only reasonable improvement would be to autodetect if it's an rpi or rpi4 board, though MAC addresses can be set in software, too (eg. Wifi MAC address randomization, or using a different vendor OUI), but I think at that point that's out of scope for plain `boardid`.

**Comment by fhunleth** [comment]
I tested this out and it doesn't work on the Raspberry Pi 4. I.e., the MAC addresses don't match the expected ones. On my Pi4, the wlan0 address is the ethernet address plus 2. Neither one look like the serial number on quick inspection.

**Comment by dognotdog** [comment]
maybe we should just remove the pi4 parts then? I don't have pi4s to test on to figure out what the scheme is.

**Comment by fhunleth** [comment]
The Raspberry Pi 4 gets the MAC address from the OTP. The algorithm is looking pretty straightforward now:

1. Read [OTP](https://www.raspberrypi.org/documentation/hardware/raspberrypi/otpbits.md) register 64/65
2. If non-zero, use that as the eth0 MAC address. Add 1 for the wlan0 MAC address. Done.
3. If zero, read the low 3 bytes of the serial number. The eth0 MAC is B8:27:EB concatenated to those bytes. For the wlan0 MAC, XOR by 0x555555 and then concatenate to B8:27:EB.

I did a quick search of the bootloader binaries and only found B8:27:EB. The other OUI's weren't there, so I'm inferring that if they're used, they're pulled from OTP 64/65. The Linux kernel drivers for WiFi and Ethernet don't have any RPi knowledge (that I've seen), so any magic settings seem like they have to come from the bootloader or VideoCore firmware.

Now that I see this, I'm wondering if the RPi Foundation will gradually switch to programming OTP 64/65 for non-Raspberry Pi 4's. I think that means that if the MAC address code isn't OTP 64/65 aware, that it will eventually break.

The `vcgencmd dump_otp` implementation isn't that long, but I don't know if there's an easier way still. I think that's for another day to figure out.

**Comment by fhunleth** [comment]
Links: 

https://www.raspberrypi.org/documentation/hardware/industrial/README.md
https://github.com/raspberrypi/firmware/wiki/Mailbox-property-interface
https://github.com/raspberrypi/userland/blob/master/host_applications/linux/apps/vcmailbox/vcmailbox.c

Command 0x00010003 looks really interesting.

**Comment by dognotdog** [comment]
@fhunleth dang seems like you found just the right thing. I've implemented a `vcmailbox` based method instead, and it seems to work for my `rpi0w`, hopefully it also works for the `rpi4`.

However, for some reason git decided throw a fit and I had to do a weird merge with 
01f8289, not sure what that was about, as it should've been straight forward. 

The remaining issue is that I'm not sure how to create the tests for this, as you'd have to spoof the `vcmailbox` program, which in and of itself is not a problem, but I'm not sure how to integrate it with the test suites. All it has to do is respond to the command line (for the rpi, different oui for rpi4; based on same serial number as other tests) with 
```
$ vcmailbox 0x00010003 6 6 0 0
0x00000020 0x80000000 0x00010003 0x00000006 0x80000006 0xf2eb27b8 0x000068f4 0x00000000
```

**Comment by fhunleth** [comment]
Thanks for pushing the updates. My plan is to take another pass tomorrow or Thursday. I feel like this is getting close to the finish line and I'm going to be making a `nerves_system_br` release real soon to push out security fixes so timing is good.

Quick comments:

1. No worries on the git issues. I'll squash everything when this is done.
2. Here's what my RPi4 did:

```
iex(5)> cmd("vcmailbox 0x00010003 6 6 0 0")
0x00000020 0x80000000 0x00010003 0x00000006 0x80000006 0x0332a6dc 0x0000b9cd 0x00000000 
0
iex(6)> ifconfig
eth0: flags=[:up, :broadcast, :running, :multicast]
    inet 192.168.7.37  netmask 255.255.255.0  broadcast 192.168.7.255
    inet 2001:470:8:3e7:dea6:32ff:fe03:cdb9  netmask ffff:ffff:ffff:ffff::
    inet fe80::dea6:32ff:fe03:cdb9  netmask ffff:ffff:ffff:ffff::
    hwaddr dc:a6:32:03:cd:b9

wlan0: flags=[:up, :broadcast, :running, :multicast]
    hwaddr dc:a6:32:03:cd:ba
```

**Comment by dognotdog** [comment]
@fhunleth the output you got on the rpi4 seems consistent with the scheme you have described (add 2 for wlan0).

I have added corresponding tests. I had to update some unrelated `_auto` testcases, too, which were calling `vcmailbox` — maybe the way I did the `vcmailbox` mockup can be improved, but it works for now.

**Comment by dognotdog** [comment]
tested on rpi0w.

**Comment by fhunleth** [comment]
Thanks again for testing. Squashed and merged manually.

**Pull request closed without merging**
