### PR TITLE
Add -b script method to execute a script that will give the boardid

### PR DESCRIPTION
**Pull request by ringlej**
We have a board that needs some custom logic for getting the serial number. This PR adds an option to run a script that is given to get a boardid string to use if available via that method.

### CODE REVIEW

**Comment by jjcarstens** [comment]
Thanks @ringlej ! Is your use-case to _only_ use this custom script or to provide as another fallback option (so that you can also specify multiple paths for trying to get a serial number)?

If it is just a different script/program to use, I'd suggest adding the `:boardid_path` config value to use this script rather than boardid (as mentioned in [`Nerves.Runtime.serial_number/0`](https://hexdocs.pm/nerves_runtime/Nerves.Runtime.html#serial_number/0))

```elixir
config :nerves_runtime, boardid_path: "/path/to/script"
```

If it is to use multiple mechanism, including the script, then order is going to matter here. If `-b script_id` is used before other arguments, it could potentially terminate early without getting to further `-b *` options and still have no serial number.

**Comment by ringlej** [comment]
Hi @jjcarstens We did look at doing that option as well, however, `boardid_path` can't be a script. It needs to be an ELF file because `System.cmd` doesn't do she-bang interpretation on the executable to be run:
https://github.com/nerves-project/nerves_runtime/blob/main/lib/nerves_runtime.ex#LL92C47-L92C47

Additionally, we will find it very useful to override the serial number used by other methods like `uboot_env`. So, really the tiered mechanisms given via `boardid.config` is still desired, with this new script method just being another priority level specified in the `boardid.config` file

**Comment by ringlej** [comment]
@jjcarstens Also, with regards to your 2nd point about ordering. I believe that the code I have in the `script_id()` function I added takes care of return false if there are any error conditions that would result in not having a board id returned, which should allow it to continue to the next method provided

**Comment by fhunleth** [comment]
Thanks!

**Comment by fhunleth** [comment]
@ringlej I added some unit tests and made a couple changes that I think should be trivial. See https://github.com/nerves-project/boardid/pull/36/files

**Comment by ringlej** [comment]
Looks good. Thanks!

**Pull request merged**
